name: Python

on:
    # mainブランチの更新時に自動で実行
    push:
        branches: gh-pages
    # Actionから手動実行も可能
    workflow_dispatch: {}

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.8"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Generate Index
              run: |
                  python generate_index.py

            - name: Commit and Push changes
              uses: EndBug/add-and-commit@v7
              with:
                  message: "Update index.html"
                  add: "index.html"
                  author_name: "Zuaki21"
                  author_email: "specialkazoo21@gmail.com"
                  signoff: true
                  force: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
